### ISSUE TITLE
Too many informations

### ISSUE THREAD

**Issue by sbonaime** [FalseIlyu/MMM-IdF-Transport#4]
With this config, I get too much informations. How can I have a smaller module ? 
  {
      //https://github.com/FalseIlyu/MMM-IdF-Transport/tree/master
      module: 'MMM-IdF-Transport',
      position: 'left',
      config: {
          apiKey: 'XXXXXXXXXXXXX', // You need to make a key on https://prim.iledefrance-mobilites.fr/fr
          stops: [
            { stopID: 'STIF:StopPoint:Q:28394:' },     
            { stopID: 'STIF:StopPoint:Q:37547:' },    
            { stopID: 'STIF:StopPoint:Q:73622:' },    
            
          ],showLabelRow: false, // Show or hide column headers
          reloadInterval: 60000 	// How often should the information be updated? (In milliseconds)
        
      }
  }, 	

![Capture d’écran 2023-10-17 à 11 27 42](https://github.com/FalseIlyu/MMM-IdF-Transport/assets/750709/58b598df-7f51-4e21-8344-112175023fe8)

**Comment by Nisnis39** [comment]
Hello maybe this will be usefull to you https://prim.iledefrance-mobilites.fr/fr/actualites/article/referentiels-arrets-et-lignes

Also, I made a little tutorial in my last answer (in moderation as of now) of this thread for an easier way to find your stop point : https://forum.magicmirror.builders/topic/17933/mmm-idf-transport-never-miss-your-train-metro-bus-tram-in-%C3%AEle-de-france-paris/2?lang=fr&loggedin=true

**Comment by sbonaime** [comment]
#5 should solve the problem
